CommerceIdeaBank_v12.11.2014Final/CommerceIdeaBank/Controllers/Contributor/ContributorHomeController.cs
using CommerceIdeaBank.Models;
using CommerceIdeaBank.DatabaseInterface.BusinessLogic;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CommerceIdeaBank.Models.ViewModels.Contributor;
using CommerceIdeaBank.GlobalConstants;
using System.Windows.Forms;
using System.IO;
using PagedList;

//Included by author


namespace CommerceIdeaBank.Controllers.Contributor
{
    //The visitors home controller
    public class ContributorHomeController : Controller
    {
        //
        // GET: /Home/                        
        ContributorAccess contributor_access = new ContributorAccess();

        public ActionResult Index( string sort_order = SortKey.ASCEND, string prev_sort_category = "", 
            string cur_sort_category = "", string current_filter = "", 
            int? page = 1, bool sort_flag = false ) 
        {            
            //User role security check
            int role = (int)HttpContext.Session["userRole"];                       

            //Ensure user is contributor
            if (role == UserRole.CONTRIBUTOR)
            {
                //Read in project list
                IEnumerable<ContributorProjectViewModel> contributor_project_list = 
                    (IEnumerable<ContributorProjectViewModel>)contributor_access.GetProjectList();                

                //For paging
                ViewBag.PreviousSortCategory = prev_sort_category;                           
                ViewBag.CurrentSortCategory = cur_sort_category;                
                ViewBag.CurrentSortOrder = sort_order;                 

                //Make sure sort is desired
                if (sort_flag == true && contributor_project_list != null)
                {
                    //Determine sort
                    switch (cur_sort_category)
                    {
                        case SortKey.PROJECT_USERNAME:
                            {
                                contributor_project_list = contributor_project_list.OrderBy(x => x.Username);                               

                                //Leave switch stmt
                                break;
                            }
                        case SortKey.PROJECT_NAME:
                            {
                                contributor_project_list = contributor_project_list.OrderBy(x => x.ProjectName);                                

                                //Leave switch stmt
                                break;
                            }
                        case SortKey.PROJECT_POST_DATE:
                            {
                                contributor_project_list = contributor_project_list.OrderBy(x => x.PostDate);                                

                                //Leave switch stmt
                                break;
                            }
                        default:
                            {
                                //No ordering
                                break;
                            }
                    }

                    if (prev_sort_category == cur_sort_category)
                    {
                        if (sort_order == SortKey.DESCEND)
                        {
                            //Reverse list
                            contributor_project_list = contributor_project_list.Reverse();

                            //Toggle sort order
                            ViewBag.CurrentSortOrder = SortKey.ASCEND;
                        }
                        else
                        {
                            //List is ascending by default. Modify CurrentSortOrder
                            ViewBag.CurrentSortOrder = SortKey.DESCEND;
                        }
                    }
                    else if (sort_order == SortKey.ASCEND)
                    {
                        //If first sort is performed, sort key must be updated

                        //List is ascending by default. Modify CurrentSortOrder
                        ViewBag.CurrentSortOrder = SortKey.DESCEND;
                    }
                    else
                    {
                        ViewBag.CurrentSortOrder = SortKey.ASCEND;
                    }
                }                

                //For paging
                int pageSize = PageStandard.PAGE_SIZE_PROJECTS;
                int pageNumber = (page ?? 1);

                if (contributor_project_list != null)
                {
                    return View(contributor_project_list.ToPagedList(pageNumber, pageSize));
                }
                else
                {
                    contributor_project_list = null;

                    return View(contributor_project_list);
                }
                                
            }
            else if (role == UserRole.ADMIN)
            {
                //Redirect to correct index
                return RedirectToAction(ActionName.AN_INDEX, PermissionSpace.PS_ADMIN_HOME);
            }
            else if (role == UserRole.AMBASSADOR)
            {
                //Redirect to correct index
                return RedirectToAction(ActionName.AN_INDEX, PermissionSpace.PS_AMBASSADOR_HOME);
            }
            else 
            {
                //Redirect to correct index
                return RedirectToAction(ActionName.AN_INDEX, PermissionSpace.PS_DEFAULT_HOME);
            }            
        }

        public ActionResult Dashboard()
        {
            //User role security check
            int role = (int)HttpContext.Session["userRole"];

            //Ensure user is contributor
            if (role == UserRole.CONTRIBUTOR)
            {
                return View();
            }
            else if (role == UserRole.ADMIN)
            {
                //Redirect to correct index
                return RedirectToAction(ActionName.AN_DASHBOARD, PermissionSpace.PS_ADMIN_HOME);
            }
            else if (role == UserRole.AMBASSADOR)
            {
                //Redirect to correct index
                return RedirectToAction(ActionName.AN_DASHBOARD, PermissionSpace.PS_AMBASSADOR_HOME);
            }
            else 
            {
                //Redirect to correct index
                return RedirectToAction(ActionName.AN_INDEX, PermissionSpace.PS_DEFAULT_HOME);
            } 
        }

        public ActionResult MyContribution( string sort_order = SortKey.ASCEND, string prev_sort_category = "",
            string cur_sort_category = "", string current_filter = "",
            int? page = 1, bool sort_flag = false )
        {
            //User role security check
            int role = (int)HttpContext.Session["userRole"];

            //Ensure user is contributor
            if (role == UserRole.CONTRIBUTOR)
            {                

                IEnumerable<ContributorProjectViewModel> contributed_projects = 
                    (IEnumerable<ContributorProjectViewModel>)contributor_access.GetProjectList();

                //For paging
                ViewBag.PreviousSortCategory = prev_sort_category;
                ViewBag.CurrentSortCategory = cur_sort_category;
                ViewBag.CurrentSortOrder = sort_order;

                //Make sure sort is desired
                if (sort_flag == true && contributed_projects != null)
                {
                    //Determine sort
                    switch (cur_sort_category)
                    {
                        case SortKey.PROJECT_USERNAME:
                            {
                                contributed_projects = contributed_projects.OrderBy(x => x.Username);

                                //Leave switch stmt
                                break;
                            }
                        case SortKey.PROJECT_NAME:
                            {
                                contributed_projects = contributed_projects.OrderBy(x => x.ProjectName);

                                //Leave switch stmt
                                break;
                            }
                        case SortKey.PROJECT_POST_DATE:
                            {
                                contributed_projects = contributed_projects.OrderBy(x => x.PostDate);

                                //Leave switch stmt
                                break;
                            }
                        default:
                            {
                                //No ordering
                                break;
                            }
                    }

                    if (prev_sort_category == cur_sort_category)
                    {
                        if (sort_order == SortKey.DESCEND)
                        {
                            //Reverse list
                            contributed_projects = contributed_projects.Reverse();

                            //Toggle sort order
                            ViewBag.CurrentSortOrder = SortKey.ASCEND;
                        }
                        else
                        {
                            //List is ascending by default. Modify CurrentSortOrder
                            ViewBag.CurrentSortOrder = SortKey.DESCEND;
                        }
                    }
                    else if (sort_order == SortKey.ASCEND)
                    {
                        //If first sort is performed, sort key must be updated

                        //List is ascending by default. Modify CurrentSortOrder
                        ViewBag.CurrentSortOrder = SortKey.DESCEND;
                    }
                    else
                    {
                        ViewBag.CurrentSortOrder = SortKey.ASCEND;
                    }
                }

                //For paging

CommerceIdeaBank_v12.11.2014Final/CommerceIdeaBank/Views/ContributorHome/ContributeIdea.cshtml
@model CommerceIdeaBank.Models.ViewModels.Contributor.ContributorProjectViewModel
@using CommerceIdeaBank.GlobalConstants
@using CommerceIdeaBank.Models.ViewModels.Contributor;

@{
    ViewBag.Title = "Contribute Idea";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    string username = (string)HttpContext.Current.Session["currentUser"];
}

@if (Request.IsAuthenticated)
{
    int role = (int)HttpContext.Current.Session["userRole"];

    if (role == UserRole.CONTRIBUTOR)
    {


        using (Html.BeginForm())
        {
            @Html.ValidationSummary(true, "Failed to Create project. Check all fields.");
            <div>
                <fieldset>
                    <legend>Contribute new idea.</legend>

                    <div class="editor-label">
                        @Html.LabelFor(x => x.ProjectName)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(x => x.ProjectName, new { @class="project_name_text" })
                        @Html.ValidationMessageFor(x => x.ProjectName)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(x => x.ProjectDesc)
                    </div>
                    <div class="editor-field">
                        @Html.TextAreaFor(x => x.ProjectDesc, new { @class = "project_desc_just_text" })
                        @Html.ValidationMessageFor(x => x.ProjectDesc)
                    </div>

                    <!-- Code for adding file -->
                    @*
                    <div >
                        @using (Html.BeginForm(ActionName.AN_ADD_FILE, PermissionSpace.PS_CONTRIBUTOR_HOME,
                            new { cur_project = Model }, FormMethod.Post, 
                            new { enctype = "multipart/form-data" }))
                        {
                            @Html.HiddenFor(x => x.Username)
                            @Html.HiddenFor(x => x.ProjectName)
                            @Html.HiddenFor(x => x.ProjectID)
                            @Html.HiddenFor(x => x.ProjectDesc)
                            @Html.HiddenFor(x => x.PostDate)
                            @Html.HiddenFor(x => x.IsArchived)
                            @Html.HiddenFor(x => x.FileList)
                            @Html.HiddenFor(x => x.BusinessJustification)

                            if (Model != null)
                            {


                                //Display previously attached files
                                if (Model.FileList != null)
                                {
                                    foreach (ContributorIdeaFileViewModel file in Model.FileList)
                                    {
                                        if (file == null) { continue; }
                                        <input type="text" class="input_textbox" value="@file.FileName" readonly />
                                    }

                                    //Append file submission button
                                    <input type="file" name="new_file" id="new_file_id" /><br />
                                    <input type="submit" id="Submit" value="Upload" formaction="AddFile" />

                                }
                                else
                                {
                                    //Append file submission button
                                    <input type="file" name="new_file" id="new_file_id" /><br />
                                    <input type="submit" id="Submit" value="Upload" formaction="AddFile" />
                                }
                            }
                            else
                            {
                                //Append file submission button
                                <input type="file" name="new_file" id="new_file_id" /><br />
                                <input type="submit" id="Submit" value="Upload" formaction="AddFile" />
                            }

                        }
                    </div>
                    *@                    

                    <div class="editor-label">
                        @Html.LabelFor(x => x.BusinessJustification)
                    </div>
                    <div class="editor-field">
                        @Html.TextAreaFor(x => x.BusinessJustification, new { @class = "project_desc_just_text" })
                        @Html.ValidationMessageFor(x => x.BusinessJustification)
                    </div>

                    @Html.HiddenFor(x => x.Username, new { @Value = @username })
                    @Html.HiddenFor(x => x.IsArchived, new { @Value = false })            
                    @Html.HiddenFor(x => x.Status, new { @Value = IdeaStatus.SUBMITTED })
                    @Html.HiddenFor(x => x.PostDate, new { @Value = DateTime.Now })

            
                    <div>
                        <input type="submit" value="Contribute" class="submit_button button" />
                    </div>

                </fieldset>
            </div>
        }


    }
    else if (role == UserRole.AMBASSADOR)
    {
        //Redirect erroneous ambassador to correct page
        Response.Redirect(Url.Action(ActionName.AN_CONTRIBUTE_IDEA, PermissionSpace.PS_AMBASSADOR_HOME));
    }
    else if (role == UserRole.ADMIN)
    {
        //Redirect erroneous admin to correct page
        Response.Redirect(Url.Action(ActionName.AN_CONTRIBUTE_IDEA, PermissionSpace.PS_ADMIN_HOME));
    }
    else
    {
        //Error. Permissions invalid. Log user off and redirect to default home
        Response.Redirect(Url.Action(ActionName.AN_PERMISSIONS_INVALID, PermissionSpace.PS_CONTRIBUTOR_HOME));
    }
}
else
{
    //If user not authenticated, route to default home
    Response.Redirect(Url.Action(ActionName.AN_INDEX, PermissionSpace.PS_DEFAULT_HOME));
}

CommerceIdeaBank_v12.11.2014Final/CommerceIdeaBank/Views/ContributorHome/Dashboard.cshtml
<!-- Include necessary view model here *** -->
@using CommerceIdeaBank.GlobalConstants

@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Request.IsAuthenticated)
{
    int role = (int)HttpContext.Current.Session["userRole"];

    if (role == UserRole.CONTRIBUTOR)
    {

        <h2 class="header">General</h2>

        <div>
            <input type="button" class="button" value="Back To List" onclick="location.href='@Url.Action(ActionName.AN_INDEX, PermissionSpace.PS_CONTRIBUTOR_HOME)'" />            
        </div>
        <hr />

        <h2 class="header">@Html.Encode(User.Identity.Name)</h2>

        <div>
            <input type="button" class="button" value="My Ideas" onclick="location.href='@Url.Action(ActionName.AN_MY_CONTRIBUTION, PermissionSpace.PS_CONTRIBUTOR_HOME)'" />
        </div>
        <hr />
    }
    else if (role == UserRole.AMBASSADOR)
    {
        //Redirect erroneous ambassador to correct page
        Response.Redirect(Url.Action(ActionName.AN_DASHBOARD, PermissionSpace.PS_AMBASSADOR_HOME));
    }
    else if (role == UserRole.ADMIN)
    {
        //Redirect erroneous admin to correct page
        Response.Redirect(Url.Action(ActionName.AN_DASHBOARD, PermissionSpace.PS_ADMIN_HOME));
    }
    else
    {
        //Error. Permissions invalid. Log user off and redirect to default home
        Response.Redirect(Url.Action(ActionName.AN_PERMISSIONS_INVALID, PermissionSpace.PS_CONTRIBUTOR_HOME));
    }
}
else
{
    //If user not authenticated, route to default home
    Response.Redirect(Url.Action(ActionName.AN_INDEX, PermissionSpace.PS_DEFAULT_HOME));
}

CommerceIdeaBank_v12.11.2014Final/CommerceIdeaBank/Views/ContributorHome/EditIdea.cshtml
@model CommerceIdeaBank.Models.ViewModels.Contributor.ContributorProjectViewModel
@using CommerceIdeaBank.GlobalConstants

@{
    ViewBag.Title = "Edit Idea";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Request.IsAuthenticated)
{
    int role = (int)HttpContext.Current.Session["userRole"];

    if (role == UserRole.CONTRIBUTOR)
    {

        <h2 class="header">Edit idea.</h2>

        using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div>
                <hr />

                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.ProjectID)
                @Html.HiddenFor(model => model.Username)
                @Html.HiddenFor(model => model.PostDate)
                @Html.HiddenFor(model => model.IsArchived)

                <table class="edit_table">
                    <tr>
                        <td class="edit_header">Project Name: </td>
                        <td class="edit_area">
                            @Html.TextBoxFor(model => model.ProjectName, new { @class = "project_name_text" })
                            @Html.ValidationMessageFor(model => model.ProjectName)
                        </td>
                    </tr>
                    <tr>
                        <td class="edit_header">Project Description: </td>
                        <td class="edit_area">
                            @Html.TextAreaFor(model => model.ProjectDesc, new { @class = "project_desc_just_text" })
                            @Html.ValidationMessageFor(model => model.ProjectDesc)
                        </td>
                    </tr>
                    <tr>
                        <td class="edit_header">Business Justification: </td>
                        <td class="edit_area">
                            @Html.TextAreaFor(model => model.BusinessJustification, new { @class = "project_desc_just_text" })
                            @Html.ValidationMessageFor(model => model.BusinessJustification)
                        </td>
                    </tr>
                </table>

                <div>
                    <input type="submit" value="Save" class="button" />
                    <input type="button" class="button" value="Back To List" onclick="location.href='@Url.Action("Index", "ContributorHome")'" />
                </div>
            </div>
        }         
    }
    else if (role == UserRole.AMBASSADOR)
    {
        //Redirect erroneous ambassador to correct page
        Response.Redirect(Url.Action(ActionName.AN_EDIT_IDEA, PermissionSpace.PS_AMBASSADOR_HOME, new { id = @Model.ProjectID }));
    }
    else if (role == UserRole.ADMIN)
    {
        //Redirect erroneous admin to correct page
        Response.Redirect(Url.Action(ActionName.AN_EDIT_IDEA, PermissionSpace.PS_ADMIN_HOME, new { id = @Model.ProjectID }));
    }
    else
    {
        //Error. Permissions invalid. Log user off and redirect to default home
        Response.Redirect(Url.Action(ActionName.AN_PERMISSIONS_INVALID, PermissionSpace.PS_CONTRIBUTOR_HOME));
    }
}
else
{
    //If user not authenticated, route to default home
    Response.Redirect(Url.Action(ActionName.AN_INDEX, PermissionSpace.PS_DEFAULT_HOME));
}

CommerceIdeaBank_v12.11.2014Final/CommerceIdeaBank/Views/ContributorHome/Index.cshtml
@model PagedList.IPagedList<CommerceIdeaBank.Models.ViewModels.Contributor.ContributorProjectViewModel>
@using CommerceIdeaBank.GlobalConstants;
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Contributor Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Request.IsAuthenticated)
{    
    int role = (int)HttpContext.Current.Session["userRole"];

    if (role == UserRole.CONTRIBUTOR)
    {
        //Display page for contributor                
        <div class="data_view">            

            <table class="contribution_table">
                <tr>
                    <th> 
                        @if (Model != null)
                        {
                            @Html.ActionLink("Project Name", ActionName.AN_INDEX, PermissionSpace.PS_CONTRIBUTOR_HOME,
                            new
                            {
                                sort_order = @ViewBag.CurrentSortOrder,
                                prev_sort_category = @ViewBag.CurrentSortCategory,
                                cur_sort_category = SortKey.PROJECT_NAME,
                                page = Model.PageNumber,
                                sort_flag = true
                            }, null)
                        }
                        else
                        {
                            @: Project Name
                        }                        
                        
                    </th>
                    <th>
                        @if (Model != null)
                        {
                            @Html.ActionLink("Username", ActionName.AN_INDEX, PermissionSpace.PS_CONTRIBUTOR_HOME,
                            new
                            {
                                sort_order = @ViewBag.CurrentSortOrder,
                                prev_sort_category = @ViewBag.CurrentSortCategory,
                                cur_sort_category = SortKey.PROJECT_USERNAME,                            
                                page = Model.PageNumber,
                                sort_flag = true
                            }, null)
                        }
                        else
                        {
                        @: Username
                        }                  
                    </th>
                    <th>  
                        @if (Model != null)
                        {
                            @Html.ActionLink("Post Date", ActionName.AN_INDEX, PermissionSpace.PS_CONTRIBUTOR_HOME,
                            new
                            {
                                sort_order = @ViewBag.CurrentSortOrder,
                                prev_sort_category = @ViewBag.CurrentSortCategory,
                                cur_sort_category = SortKey.PROJECT_POST_DATE,
                                page = Model.PageNumber,
                                sort_flag = true
                            }, null)
                        }
                        else
                        {
                            @: Post Date
                        }                      
                        
                    </th>
                </tr>
                @if (Model != null && Model.ToList().Count != 0)
                {
                    foreach (var item in Model)
                    {
                        if (item == null)
                        {
                            continue;
                        }
                        else
                        {
                            <tr>
                                <td class="project_name" id="project_name_col">
                                    @Html.ActionLink(item.ProjectName, ActionName.AN_VIEW_IDEA, new { id = item.ProjectID })
                                    <div class="description_field">
                                        Description:
                                        @Html.DisplayFor(modelItem => item.ProjectDesc)
                                    </div>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Username)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PostDate)
                                </td>
                            </tr>
                        }
                    }
                }
                else if (Model == null)
                {
                    //No ideas have been submitted yet
                    <tr>
                        <td>There are no ideas yet. You should be the first to contribute! :-) </td>
                    </tr>
                }
                else if (Model.ToList().Count == 0)
                {
                    //No ideas have been submitted yet
                    <tr>
                        <td>There are no ideas yet. You should be the first to contribute! :-) </td>
                    </tr>
                }
                
            </table>

            @if (ViewBag.CurrentSortCategory == ViewBag.PreviousSortCategory)
            {
                ViewBag.temp = ViewBag.CurrentSortCategory;                
                
                //Toggle sort order
                if ( ViewBag.CurrentSortOrder == SortKey.ASCEND )
                {
                    ViewBag.tempSortOrder = SortKey.DESCEND;
                }
                else
                {
                    ViewBag.tempSortOrder = SortKey.ASCEND;
                }                
            }
            else
            {
                ViewBag.temp = ViewBag.PreviousSortCategory;
            }
            
            @if (Model != null)
            {
                <br />
                @:Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                @Html.PagedListPager(Model, page => Url.Action(ActionName.AN_INDEX, PermissionSpace.PS_CONTRIBUTOR_HOME,
                        new { 
                              page,
                              sort_order = @ViewBag.tempSortOrder,                                                     
                              prev_sort_category = @ViewBag.temp,
                              cur_sort_category = @ViewBag.CurrentSortCategory, 
                              sort_flag = true
                        }, null),
                        new PagedListRenderOptions { DisplayLinkToIndividualPages = true })    
            }
            
        </div>    
    }
    else if (role == UserRole.AMBASSADOR)
    {
        //Redirect erroneous ambassador to correct page
        Response.Redirect(Url.Action(ActionName.AN_INDEX, PermissionSpace.PS_AMBASSADOR_HOME));
    }
    else if (role == UserRole.ADMIN)
    {
        //Redirect erroneous admin to correct page
        Response.Redirect(Url.Action(ActionName.AN_INDEX, PermissionSpace.PS_ADMIN_HOME));
    }
    else
    {
        //Error. Permissions invalid. Log user off and redirect to default home
        Response.Redirect(Url.Action(ActionName.AN_PERMISSIONS_INVALID, PermissionSpace.PS_CONTRIBUTOR_HOME));
    }    
}
else
{
    //If user not authenticated, route to default home
    Response.Redirect(Url.Action(ActionName.AN_INDEX, PermissionSpace.PS_DEFAULT_HOME));
}

CommerceIdeaBank_v12.11.2014Final/CommerceIdeaBank/Views/ContributorHome/ViewIdea.cshtml
@model CommerceIdeaBank.Models.ViewModels.Contributor.ContributorProjectViewModel
@using CommerceIdeaBank.GlobalConstants

@{
    ViewBag.Title = "Idea Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Request.IsAuthenticated)
{
    int role = (int)HttpContext.Current.Session["userRole"];

    if (role == UserRole.CONTRIBUTOR)
    {

        <h1 class="header">Project details.</h1>
        <h2>@Html.DisplayFor(model => model.ProjectName)</h2>
        <hr />

        <div>
            <table class="view_table">
                <tr>
                    <td>Username: </td>
                    <td>@Html.DisplayFor(model => model.Username)</td>
                </tr>
                <tr>
                    <td>Description: </td>
                    <td>@Html.DisplayFor(model => model.ProjectDesc)</td>
                </tr>
                <tr>
                    <td>Justification: </td>
                    <td>@Html.DisplayFor(model => model.BusinessJustification)</td>
                </tr>
                <tr>
                    <td>Post Date: </td>
                    <td>@Html.DisplayFor(model => model.PostDate)</td>
                </tr>
            </table>
        </div>

        <div>
            @if (Request.IsAuthenticated)
            {
                string username = (string)HttpContext.Current.Session["currentUser"];

                if (username == @Html.Encode(Model.Username))
                {
                    <input type="button" class="button" value="Edit Idea" onclick="location.href='@Url.Action(ActionName.AN_EDIT_IDEA, PermissionSpace.PS_CONTRIBUTOR_HOME, new { id = Model.ProjectID })'" />
                }

                <input type="button" class="button" value="Back To List" onclick="location.href='@Url.Action(ActionName.AN_INDEX, PermissionSpace.PS_CONTRIBUTOR_HOME)'" />
            }
        </div>
    
    }
    else if (role == UserRole.AMBASSADOR)
    {
        //Redirect erroneous ambassador to correct page
        Response.Redirect(Url.Action(ActionName.AN_VIEW_IDEA, PermissionSpace.PS_AMBASSADOR_HOME, new { id = @Model.ProjectID }));
    }
    else if (role == UserRole.ADMIN)
    {
        //Redirect erroneous admin to correct page
        Response.Redirect(Url.Action(ActionName.AN_VIEW_IDEA , PermissionSpace.PS_ADMIN_HOME, new { id = @Model.ProjectID }));
    }
    else
    {
        //Error. Permissions invalid. Log user off and redirect to default home
        Response.Redirect(Url.Action(ActionName.AN_PERMISSIONS_INVALID, PermissionSpace.PS_CONTRIBUTOR_HOME));
    }
}
else
{
    //If user not authenticated, route to default home
    Response.Redirect(Url.Action(ActionName.AN_INDEX, PermissionSpace.PS_DEFAULT_HOME));
}